[project]
name = "rl-frozenlake-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=26.1.0",
    "gymnasium[toy-text]>=1.2.3",
]
